version: "3.7"
services:
  user_service:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo:latest"
    restart: always
    ports:
      - "27017:27017"